#ifndef MSPM0_CLOCK_CONFIG_H
#define MSPM0_CLOCK_CONFIG_H

#define ENABLE 1
#define DISABLE 0

#define FLASHWAIT_NO_FLASH_STATE 0
#define FLASHWAIT_ONE_FLASH_STATE 1
#define FLASHWAIT_TWO_FLASH_STATE 2

#ifndef MSPM0_FLASHWAIT_VALUE
#define MSPM0_FLASHWAIT_VALUE FLASHWAIT_TWO_FLASH_STATE
#endif

#define SYSPLLREF_SEL_SYSOSC 0
#define SYSPLLREF_SEL_HFCLK 1

#ifndef MSPM0_SYSPLL_REF_SEL
#define MSPM0_SYSPLL_REF_SEL SYSPLLREF_SEL_SYSOSC
#endif

#define SYSPLLREF_PDIV_0 0
#define SYSPLLREF_PDIV_2 1
#define SYSPLLREF_PDIV_4 2
#define SYSPLLREF_PDIV_8 3

#ifndef MSPM0_SYSPLL_PDIV
#define MSPM0_SYSPLL_PDIV SYSPLLREF_PDIV_2
#endif

#ifndef MSPM0_SYSPLL_QDIV
#define MSPM0_SYSPLL_QDIV 4U
#endif

#define CLK1_SYSPLLCLK1_DIVIDEBY_2 0
#define CLK1_SYSPLLCLK1_DIVIDEBY_4 1
#define CLK1_SYSPLLCLK1_DIVIDEBY_6 2
#define CLK1_SYSPLLCLK1_DIVIDEBY_8 3
#define CLK1_SYSPLLCLK1_DIVIDEBY_10 4
#define CLK1_SYSPLLCLK1_DIVIDEBY_12 5
#define CLK1_SYSPLLCLK1_DIVIDEBY_14 6
#define CLK1_SYSPLLCLK1_DIVIDEBY_16 7
#define CLK1_SYSPLLCLK1_DIVIDEBY_18 8
#define CLK1_SYSPLLCLK1_DIVIDEBY_20 9
#define CLK1_SYSPLLCLK1_DIVIDEBY_22 10
#define CLK1_SYSPLLCLK1_DIVIDEBY_24 11
#define CLK1_SYSPLLCLK1_DIVIDEBY_26 12
#define CLK1_SYSPLLCLK1_DIVIDEBY_28 13
#define CLK1_SYSPLLCLK1_DIVIDEBY_30 14
#define CLK1_SYSPLLCLK1_DIVIDEBY_32 15

#ifndef MSPM0_SYSPLL_RDIVCLK1
#define MSPM0_SYSPLL_RDIVCLK1 CLK1_SYSPLLCLK1_DIVIDEBY_2
#endif

#define CLK2X_SYSPLLCLK1_DIVIDEBY_1 0
#define CLK2X_SYSPLLCLK1_DIVIDEBY_2 1
#define CLK2X_SYSPLLCLK1_DIVIDEBY_3 2
#define CLK2X_SYSPLLCLK1_DIVIDEBY_4 3
#define CLK2X_SYSPLLCLK1_DIVIDEBY_5 4
#define CLK2X_SYSPLLCLK1_DIVIDEBY_6 5
#define CLK2X_SYSPLLCLK1_DIVIDEBY_7 6
#define CLK2X_SYSPLLCLK1_DIVIDEBY_8 7
#define CLK2X_SYSPLLCLK1_DIVIDEBY_9 8
#define CLK2X_SYSPLLCLK1_DIVIDEBY_10 9
#define CLK2X_SYSPLLCLK1_DIVIDEBY_11 10
#define CLK2X_SYSPLLCLK1_DIVIDEBY_12 11
#define CLK2X_SYSPLLCLK1_DIVIDEBY_13 12
#define CLK2X_SYSPLLCLK1_DIVIDEBY_14 13
#define CLK2X_SYSPLLCLK1_DIVIDEBY_15 14
#define CLK2X_SYSPLLCLK1_DIVIDEBY_16 15

#ifndef MSPM0_SYSPLL_RDIVCLK2X
#define MSPM0_SYSPLL_RDIVCLK2X CLK2X_SYSPLLCLK1_DIVIDEBY_2
#endif

#ifndef MSPM0_SYSPLL_ENABLE_CLK1
#define MSPM0_SYSPLL_ENABLE_CLK1 ENABLE
#endif

#ifndef MSPM0_SYSPLL_ENABLE_CLK2X
#define MSPM0_SYSPLL_ENABLE_CLK2X ENABLE
#endif

#ifndef MSPM0_HSCLK_USE_MCLK2XVCO
#define MSPM0_HSCLK_USE_MCLK2XVCO ENABLE
#endif

#ifndef MSPM0_SYSPLL_STATE
#define MSPM0_SYSPLL_STATE ENABLE
#endif

#ifndef MSPM0_HSCLK_SEL
#define MSPM0_HSCLK_SEL 0U
#endif

#ifndef MSPM0_MCLK_MDIV
#define MSPM0_MCLK_MDIV 0U
#endif

#ifndef MSPM0_MCLK_UDIV
#define MSPM0_MCLK_UDIV 0U
#endif

#ifndef MSPM0_MCLK_USE_HSCLK
#define MSPM0_MCLK_USE_HSCLK ENABLE
#endif

#if MSPM0_SYSPLL_PDIV == SYSPLLREF_PDIV_1
  // PDIV=/1 -> fLOOPIN = 32MHz
  #define MSPM0_SYSPLLPARAM0_ADDR 0x41C40034U
  #define MSPM0_SYSPLLPARAM1_ADDR 0x41C40038U
#elif MSPM0_SYSPLL_PDIV == SYSPLLREF_PDIV_2
  // PDIV=/2 -> fLOOPIN = 16MHz.
  #define MSPM0_SYSPLLPARAM0_ADDR 0x41C4002CU
  #define MSPM0_SYSPLLPARAM1_ADDR 0x41C40030U
#elif MSPM0_SYSPLL_PDIV == SYSPLLREF_PDIV_4
  // PDIV=/4 -> fLOOPIN = 8MHz
  #define MSPM0_SYSPLLPARAM0_ADDR 0x41C40024U
  #define MSPM0_SYSPLLPARAM1_ADDR 0x41C40028U
#elif MSPM0_SYSPLL_PDIV == SYSPLLREF_PDIV_8
  // PDIV=/8 -> fLOOPIN = 4MHz
  #define MSPM0_SYSPLLPARAM0_ADDR 0x41C4001CU
  #define MSPM0_SYSPLLPARAM1_ADDR 0x41C40020U
#else
  #error "MSPM0_SYSPLL_PDIV has no matching SYSPLLPARAM trim addresses — add one or fix PDIV"
#endif

#endif
